[window]
startup_mode = "Windowed"
decorations = "None"

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }

[colors]
vi_mode_cursor = { cursor = "#ff00ff" }

[keyboard]
bindings = [
  { key = "q", mods = "Control", action = "Quit" },
  { key = ";", mods = "Control", action = "ToggleViMode" },
]

[general]
import = [
  "~/.config/alacritty/themes/themes/purple.toml"
]

[terminal]

[terminal.shell]
program = "/bin/fish"
args = ["-l", "-c", "zellij"]

