import = ["~/.config/alacritty/themes/themes/github_dark.toml"]

[window]
startup_mode = "Fullscreen"
decorations = "None"

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "q", mods = "Control", action = "Quit" },
  { key = "/", mods = "Control", action = "ToggleViMode" },
]

[shell]
program = "/bin/fish"
args = ["-l", "-c", "zellij"]

